apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-node02-data-pv-volume
  labels:
    type: local
spec:
  storageClassName: shared-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /storage/data/mrr/mongodb-ha/node02/data
