apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-data-pv-volume
  labels:
    type: local
spec:
  storageClassName: shared-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /storage/data/rdbs/mssql/data
