apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-config-pv-claim
spec:
  storageClassName: shared-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
