apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.network/elk.net: "true"
        io.kompose.service: elasticsearch
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms1000m -Xmx1000m
            - name: bootstrap.memory_lock
              value: "true"
            - name: discovery.type
              value: single-node
            - name: xpack.monitoring.enabled
              value: "false"
            - name: xpack.security.enabled
              value: "false"
          image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:9200
            failureThreshold: 10
            periodSeconds: 10
            timeoutSeconds: 10
          name: elasticsearch
          ports:
            - containerPort: 9200
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data-pv-claim
            - mountPath: /usr/share/elasticsearch/config/hunspell
              name: elasticsearch-hunspell-pv-claim
            - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              name: elasticsearch-config
              subPath: elasticsearch.yml
              readOnly: true
      volumes:
        - name: elasticsearch-data-pv-claim
          persistentVolumeClaim:
            claimName: elasticsearch-data-pv-claim
        - name: elasticsearch-hunspell-pv-claim
          persistentVolumeClaim:
            claimName: elasticsearch-hunspell-pv-claim
        - name: elasticsearch-config
          configMap:
            name: elasticsearch-config
      restartPolicy: Always
      serviceAccountName: ""
      nodeSelector:
        kubernetes.io/hostname: ubuntu01
status: {}
