apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-hunspell-pv-claim
spec:
  storageClassName: shared-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
